project_id = "vsarkftwkontkfcodbyk"

[functions.send-email-update-confirmation]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.send-forum-notification]
verify_jwt = false

[functions.create-demo-tactical-game]
verify_jwt = false

[functions.generate-ai-move]
verify_jwt = false

[functions.rebuild-tactical-game]
verify_jwt = false
